services:
  - type: web
    name: codeswitch
    env: node
    plan: starter
    buildCommand: |
      npm install --include=dev
      cd client
      npm install
      npm run build
      cd ..
      npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.x
    build:
      nodeVersion: 18
    healthCheckPath: /api/health
    autoDeploy: true
